name: Build and Test - Windows/mingw (short)

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build_and_test:
    runs-on: windows-latest

    defaults:
      run:
        # Use MSYS2 as default shell
        shell: msys2 {0}

    strategy:
      matrix:
        msystem: [MINGW64, MINGW32]
        include:
          - msystem: MINGW64
            target-prefix: mingw-w64-x86_64
          - msystem: MINGW32
            target-prefix: mingw-w64-i686

    steps:
    - uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        release: false
        install: >-
            base-devel
            ${{ matrix.target-prefix }}-cmake
            ${{ matrix.target-prefix }}-gcc
            ${{ matrix.target-prefix }}-gcc-fortran
            ${{ matrix.target-prefix }}-openblas
            ${{ matrix.target-prefix }}-suitesparse

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory
      run: |
        cmake \
          -B ${GITHUB_WORKSPACE}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_C_FLAGS=-Wno-deprecated-declarations \
          -DBUILD_FORTRAN_MODULE_INTERFACE=ON \
          -DSUNDIALS_BUILD_WITH_PROFILING=ON \
          -DSUNDIALS_LOGGING_LEVEL=2 \
          -DSUNDIALS_TEST_UNITTESTS=OFF \
          -DEXAMPLES_ENABLE_CXX=ON \
          -DENABLE_KLU=ON

    - name: Build
      # Build program
      run: cmake --build ${GITHUB_WORKSPACE}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests
      run: ctest --output-on-failure
